### DISCUSSION TITLE
[Mobile] Make the tab list reachable with just a thumb

### DISCUSSION THREAD

**Discussion by Anarchtism** [oxdc/obsidian-vertical-tabs#152] [Ideas]
Currently the tab list comes down from the top of the screen. If it instead was at the bottom of the screen, it'd be easier to use on mobile without having to use a second hand to access.

**Comment by Anarchtism** [comment]
While I wait...

```CSS
@media only screen and (max-width: 768px) {
	.obsidian-vertical-tabs-container {
		width: 100%;
		position: absolute;
		bottom: 0;
		padding-bottom: 50px;
	}
}
```

I use the same CSS snippet file on mobile and desktop, so `@media only screen and (max-width: 768px)` makes it only apply on mobile.

**Reply by Anarchtism** [reply]
Oh, my CSS causes issues... The buttons on the bottom row (with Zen Mode and stuff) are no longer pressable...

**Reply by Anarchtism** [reply]
```CSS
@media only screen and (max-width: 768px) {
	.obsidian-vertical-tabs-container {
		width: 100%;
		position: absolute;
		bottom: 48px;
	}
}
```

I guess this will work for now...
