### DISCUSSION TITLE
Setting to move or hide toolbar

### DISCUSSION THREAD

**Discussion by Mercencium** [oxdc/obsidian-vertical-tabs#59] [Q&A] [answered]
The nav header takes a lot of vertical space and I don't use it,
having an option to either move it to the bottom after all tabs or hide completely would be nice.

![image](https://github.com/user-attachments/assets/15f385c9-644e-4052-9edf-c57d4e167732)

**Comment by oxdc** [comment, marked as answer]
Hi! An easy way to do this is using the following CSS snippet:

```css
.vertical-tabs .nav-header {
    display: none;
}
```

[Here's the official guide for adding CSS snippets.](https://help.obsidian.md/Extending+Obsidian/CSS+snippets)

As a reminder, I strongly advise you **NOT** to do so. This toolbar is a part of Obsidian UI. You will see the same kind of toolbars in build-in views, such as Files, Bookmarks and Tags. In the near future, several important buttons will be added here and hiding them will break the UI and its functionality.

As I said, hiding the toolbar will completely break the UX, therefore, I am afraid that this option will not be added to the settings. As an alternative, you may want to reduce the space between toolbar and vertical tabs by using the following snippet:

```css
.obsidian-vertical-tabs-container {
    padding-top: 0;
}
```

> move it to the bottom after all tabs

Some themes offer this feature. If you see the toolbar on the top, it means that your theme designer decided this way. *Vertical Tabs* will show the toolbar at the same location as all the remaining parts of Obsidian to offer users a consistent UI. You may manually overwrite this with this snippet:

```css
.vertical-tabs .nav-header {
    order: 10;
    margin-top: auto;
    margin-bottom: 5px;  /* optional */
}
```

I'll close this issue now. If you need further help, please comment below. Thank you for your appreciation!
