### ISSUE TITLE
Add responsive grid layout and improved Zen mode compatibility for Mission Control view

### ISSUE THREAD

**Issue by PandaNocturne** [oxdc/obsidian-vertical-tabs#159]
### Enhancement Checklist

- [x] I have searched existing issues and this is not a duplicate
- [x] I am reporting a simple enhancement or improvement within Vertical Tabs, not requesting new features or addressing compatibility issues with other plugins
- [x] I understand that proposals for new features should be discussed in the ‘Discussions’ tab
- [x] I understand that compatibility issues with other plugins should be posted as a ‘Compatibility’ issue

### Enhancement Type

Design

### Enhancement Description

![Image](https://github.com/user-attachments/assets/1288f07b-193b-4c63-aad6-24f50ca3536f)

I found a new command called `set current groups as mission control view`, which allows you to view a card layout of all pages in the current group. However, the default does not support adaptive layout. I modified the layout style using a grid layout and found that it works very well. Here is the effect of my modification:

![Image](https://github.com/user-attachments/assets/96fa082e-bee4-487b-af91-6bcb09fc06cd)

With this approach, I can effectively manage pages using both the `mission control view` and `zen mode` commands, as demonstrated below; it works exceptionally well.

![Image](https://github.com/user-attachments/assets/6ca52207-8bb9-4a36-8a3e-e3bb1250212b)

### Motivation

This enhancement improves the page management experience for users of Vertical Tabs, particularly in task management. With the adaptive layout, users can more effectively view and organize multiple pages, thereby increasing work efficiency.

This is the style I modified.
```css
.workspace-tabs.vt-mission-control-view {
  --vt-mission-control-view-leaf-gap: 20px;
  --vt-mission-control-view-leaf-zoom-factor: 0.5;
  --vt-mission-control-view-leaf-height: 600px;
  --vt-mission-control-view-leaf-width: 400px;


  .workspace-tab-container {
    padding: 30px;
    height: fit-content;
    max-height: 90%;
    overflow: auto !important;


    width: 100% !important;
    flex: 0 0 auto;
    display: grid;
    gap: var(--vt-mission-control-view-leaf-gap);
    grid-template-columns: repeat(auto-fill, minmax(var(--vt-mission-control-view-leaf-width), 1fr));

    .workspace-leaf {
      border-radius: 10px;
      display: block !important;
      border: 2px solid var(--background-modifier-border);
      min-height: var(--vt-mission-control-view-leaf-heigh) !important;
      min-width: 100% !important;
    }
  }
}

.vt-mission-control-view .cg-note-toolbar-container {
  display: none;
}

```
